package Presentacion;

import LogicaNegocio.LogicaTransaccion;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ATMApp extends javax.swing.JFrame {

    
    private String cuentaAutenticada;


    public ATMApp() throws IOException {
        initComponents();
        setLocationRelativeTo(null); 
        new LogicaTransaccion();

    }

    public void setCuentaAutenticada(String cuenta, String nombreUsuario, String pin) {
        this.cuentaAutenticada = cuenta;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnDepositar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnTransferir1 = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnHisotrial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmovimientos = new javax.swing.JTable();
        Btntipodecambio = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setToolTipText("");

        btnDepositar.setBackground(new java.awt.Color(255, 255, 255));
        btnDepositar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(0, 0, 0));
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar Saldo");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnTransferir1.setBackground(new java.awt.Color(255, 255, 255));
        btnTransferir1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnTransferir1.setForeground(new java.awt.Color(0, 0, 0));
        btnTransferir1.setText("Transferir");
        btnTransferir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferir1ActionPerformed(evt);
            }
        });

        btnRetirar.setBackground(new java.awt.Color(255, 255, 255));
        btnRetirar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnHisotrial.setBackground(new java.awt.Color(255, 255, 255));
        btnHisotrial.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnHisotrial.setForeground(new java.awt.Color(0, 0, 0));
        btnHisotrial.setText("Movimientos");
        btnHisotrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHisotrialActionPerformed(evt);
            }
        });

        tblmovimientos.setBackground(new java.awt.Color(255, 255, 255));
        tblmovimientos.setForeground(new java.awt.Color(0, 0, 0));
        tblmovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Monto", "Movimiento", "Monto transacción", "Monto final "
            }
        ));
        jScrollPane1.setViewportView(tblmovimientos);

        Btntipodecambio.setBackground(new java.awt.Color(255, 255, 255));
        Btntipodecambio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Btntipodecambio.setForeground(new java.awt.Color(0, 0, 0));
        Btntipodecambio.setText("Consultar tipo de cambio");
        Btntipodecambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntipodecambioActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("BIENVENIDO");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A continuacion se muestran las opciones disponibles que puedes realizar con tu dinero. Seleccione lo necesario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTransferir1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHisotrial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(Btntipodecambio, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransferir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btntipodecambio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHisotrial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
       
        String montoStr = JOptionPane.showInputDialog(this, "Ingrese el monto a depositar:");

      
        if (montoStr == null || montoStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            
            System.out.println("Monto ingresado (antes de convertir): " + montoStr);

           
            montoStr = montoStr.replace(",", ".");

            
            if (!montoStr.matches("\\d+(\\.\\d+)?")) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

           
            double monto = Double.parseDouble(montoStr);

           
            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser un número positivo.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

           
            LogicaTransaccion logicaTransaccion = new LogicaTransaccion();

          
            double saldoAnterior = logicaTransaccion.consultarSaldo(cuentaAutenticada);

          
            double saldoNuevo = saldoAnterior + monto;

            
            logicaTransaccion.depositar(cuentaAutenticada, monto, saldoAnterior, saldoNuevo);

            JOptionPane.showMessageDialog(this,
                    "Depósito exitoso.\nSaldo anterior: " + saldoAnterior + "\nSaldo nuevo: " + saldoNuevo,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
        
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnHisotrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHisotrialActionPerformed
     
    if (cuentaAutenticada == null || cuentaAutenticada.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay cuenta autenticada.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        
        LogicaTransaccion logicaHistorial = new LogicaTransaccion();
        JDialog MovimientosDialog = new JDialog();

        ArrayList<String[]> movimientos = logicaHistorial.leerBalance(cuentaAutenticada);

        if (movimientos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron movimientos para esta cuenta.", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

  
        DefaultTableModel model = (DefaultTableModel) tblmovimientos.getModel();


        model.setRowCount(0);

        model.setColumnIdentifiers(new String[]{"Fecha", "Monto Transacción", "Monto Anterior", "Movimiento", "Monto Final"});

      
        for (String[] movimiento : movimientos) {
      
          
            String montoAnterior = movimiento[0];
            String montoNuevo = movimiento[1];
            String tipoMovimiento = movimiento[2];
            String montoTransaccion = movimiento[3];
            String fecha = movimiento[4];

            
            model.addRow(new Object[]{fecha, montoTransaccion, montoAnterior, tipoMovimiento, montoNuevo});
        }
        MovimientosDialog.setVisible(true);

    } catch (IOException ex) {
        
        JOptionPane.showMessageDialog(this, "Error al cargar el historial: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        Logger.getLogger(ATMApp.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnHisotrialActionPerformed

    private void btnTransferir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferir1ActionPerformed
      
        String cuentaDestino = JOptionPane.showInputDialog(this, "Ingrese el número de cuenta de destino:");

    
        if (cuentaDestino == null || cuentaDestino.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una cuenta de destino.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String montoStr = JOptionPane.showInputDialog(this, "Ingrese el monto a transferir:");


        if (montoStr == null || montoStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            System.out.println("Monto ingresado (antes de convertir): " + montoStr);


            montoStr = montoStr.replace(",", ".");


            if (!montoStr.matches("\\d+(\\.\\d+)?")) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }


            double monto = Double.parseDouble(montoStr);

    
            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser un número positivo.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            LogicaTransaccion logicaTransaccion = new LogicaTransaccion();

            double saldoOrigen = logicaTransaccion.consultarSaldo(cuentaAutenticada);

            if (saldoOrigen < monto) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente en la cuenta de origen.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double saldoDestino = logicaTransaccion.consultarSaldo(cuentaDestino);

            logicaTransaccion.transferir(cuentaAutenticada, cuentaDestino, monto, saldoOrigen, saldoDestino);

            JOptionPane.showMessageDialog(this,
                    "Transferencia exitosa.\nCuenta de origen: " + cuentaAutenticada + "\nCuenta de destino: " + cuentaDestino
                    + "\nMonto transferido: " + monto,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTransferir1ActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        String montoStr = JOptionPane.showInputDialog(this, "Ingrese el monto a retirar:");

        if (montoStr == null || montoStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            System.out.println("Monto ingresado (antes de convertir): " + montoStr);

            montoStr = montoStr.replace(",", ".");

            if (!montoStr.matches("\\d+(\\.\\d+)?")) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double monto = Double.parseDouble(montoStr);

            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser un número positivo.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            LogicaTransaccion logicaTransaccion = new LogicaTransaccion();

            double saldoAnterior = logicaTransaccion.consultarSaldo(cuentaAutenticada);

            if (saldoAnterior < monto) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente para realizar el retiro.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double saldoNuevo = saldoAnterior - monto;

            logicaTransaccion.retirar(cuentaAutenticada, monto, saldoAnterior, saldoNuevo);

            JOptionPane.showMessageDialog(this,
                    "Retiro exitoso.\nSaldo anterior: " + saldoAnterior + "\nSaldo nuevo: " + saldoNuevo,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (cuentaAutenticada == null || cuentaAutenticada.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay cuenta autenticada.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            LogicaTransaccion logicaTransaccion = new LogicaTransaccion();

            double saldo = logicaTransaccion.consultarSaldo(cuentaAutenticada);

            JOptionPane.showMessageDialog(this,
                    "El saldo de la cuenta  " + cuentaAutenticada + " es: " + saldo,
                    "Consulta de saldo", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al consultar el saldo: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void BtntipodecambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntipodecambioActionPerformed
       Frm_tipo_cambio cambio = new Frm_tipo_cambio();
            cambio.setVisible(true);
            this.dispose();  
    }//GEN-LAST:event_BtntipodecambioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          VentanaLogin login = new VentanaLogin();
          login.setVisible(true);
          this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ATMApp().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ATMApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btntipodecambio;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnHisotrial;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnTransferir1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmovimientos;
    // End of variables declaration//GEN-END:variables

}
