
package Presentacion;
import Servicios.ServicioLogicaTipoCambio;
import LogicaNegocio.LogicaTipoCambio;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dmsda
 */
public class Frm_tipo_cambio extends javax.swing.JFrame {

     private final String token = "22OOIA2PA1";
    /**
     * Creates new form Frm_tipo_cambio
     */
    public Frm_tipo_cambio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnconsultarconversion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dtinicio = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblresultados = new javax.swing.JTable();
        dtfinal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Consultar el tipo de cambio por fechas");

        btnconsultarconversion.setBackground(new java.awt.Color(255, 255, 255));
        btnconsultarconversion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnconsultarconversion.setForeground(new java.awt.Color(0, 0, 0));
        btnconsultarconversion.setText("Consultar");
        btnconsultarconversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarconversionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de inicio");

        dtinicio.setBackground(new java.awt.Color(255, 255, 255));
        dtinicio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        tblresultados.setBackground(new java.awt.Color(35, 148, 176));
        tblresultados.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblresultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha ", "Compra", "Venta"
            }
        ));
        jScrollPane1.setViewportView(tblresultados);

        dtfinal.setBackground(new java.awt.Color(255, 255, 255));
        dtfinal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha final");

        btnlimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnregresar.setBackground(new java.awt.Color(255, 255, 255));
        btnregresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnregresar.setForeground(new java.awt.Color(0, 0, 0));
        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(436, Short.MAX_VALUE)
                .addComponent(btnlimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnregresar)
                .addGap(136, 136, 136))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dtinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dtfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(174, 174, 174))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnconsultarconversion)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiar)
                    .addComponent(btnregresar))
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(btnconsultarconversion))
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(dtinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(dtfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarconversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarconversionActionPerformed

        // Inicializa la lógica de negocio
        ServicioLogicaTipoCambio tipocambio= new LogicaTipoCambio();

        // Obtiene las fechas de iniciso y final desde los componentes de la interfaz
        Date fechaInicioDate = dtinicio.getDate();
        Date fechaFinalDate = dtfinal.getDate();

        // Verifica si las fechas seleccionadas no son null
        if (fechaInicioDate == null || fechaFinalDate == null) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione ambas fechas.");
            return; // Sale del evento si alguna fecha no está seleccionada
        }

        // Verifica que la fecha de inicio sea anterior o igual a la fecha final
        if (fechaInicioDate.after(fechaFinalDate)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio debe ser anterior o igual a la fecha final.");
            return; // Sale del evento si la fecha de inicio es después de la fecha final
        }

        // Define el formato de fecha que se va a utilizar para mostrar en la tabla
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fechaInicioDate); // Inicializa el calendario con la fecha de inicio

        // Itera sobre el rango de fechas desde la fecha de inicio hasta la fecha final
        while (!calendar.getTime().after(fechaFinalDate)) {
            Date fechaActual = calendar.getTime(); // Obtiene la fecha actual del calendario
            String fechaActualStr = dateFormat.format(fechaActual); // Convierte la fecha a formato String

            try {
                // Llama a la lógica de negocio para obtener el tipo de cambio de compra y venta
                String resultadoCompra = tipocambio.obtenerTipoCambio("317", fechaActualStr, fechaActualStr, "David", "N", "dmsdavidmonterososa@gmail.com", token);
                String resultadoVenta = tipocambio.obtenerTipoCambio("318", fechaActualStr, fechaActualStr, "David", "N", "dmsdavidmonterososa@gmail.com", token);

                // Actualiza la tabla con los resultados de compra y venta
                DefaultTableModel tableModel = (DefaultTableModel) tblresultados.getModel();
                tableModel.addRow(new Object[]{fechaActualStr, resultadoCompra, resultadoVenta});
            } catch (Exception ex) {
                // Muestra un mensaje de error si ocurre un problema al obtener el tipo de cambio
                JOptionPane.showMessageDialog(this, "Error al obtener tipo de cambio para " + fechaActualStr + ": " + ex.getMessage());
            }

            // Avanza al siguiente día
            calendar.add(Calendar.DAY_OF_MONTH, 1);
        }
    }//GEN-LAST:event_btnconsultarconversionActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
       // Limpia los campos de fecha
    dtinicio.setDate(null); // Limpia la fecha de inicio
    dtfinal.setDate(null);  // Limpia la fecha final

    // Limpia los resultados de la tabla
    DefaultTableModel tableModel = (DefaultTableModel) tblresultados.getModel();
    tableModel.setRowCount(0); // Elimina todas las filas de la tabla
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
         try {
             ATMApp atm = new ATMApp();
             
             atm.setVisible(true);      
             this.dispose();
         } catch (IOException ex) {
             Logger.getLogger(Frm_tipo_cambio.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_tipo_cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_tipo_cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_tipo_cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_tipo_cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_tipo_cambio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultarconversion;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnregresar;
    private com.toedter.calendar.JDateChooser dtfinal;
    private com.toedter.calendar.JDateChooser dtinicio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblresultados;
    // End of variables declaration//GEN-END:variables
}
